install.packages(c("bookdown",
                   "ggrepel",
                   "knitr",
                   "pheatmap",
                   "RColorBrewer",
                   "readxl",
                   "reshape2",
                   "rmarkdown",
                   "tidyverse"))
source("https://bioconductor.org/biocLite.R")
biocLite(c("BiocStyle",
           "biomaRt",
           "DESeq2",
           "edgeR",
           "tximport",
           "vsn",
           "hbc/CHBUtils",
           "steinbaugh/basejump"))
