```{r setup, echo=FALSE}
opts_chunk$set(tidy=TRUE, cache=FALSE, highlight=TRUE, figalign="center", warning=FALSE,  error=TRUE, message=FALSE,
               echo=FALSE, fig.height=11, fig.width=11)
```

### GWASeq exploratory plots

Summary distribution plots of GWASeq variant results. Some common conventions used:

- Low count variants are defined as present in less than 10 samples. Conversely, high count variants are in more than 10.
- bait/offbait specify if regions fall into bait regions or in target regions outside of the baits.


```{r sample_variants_plot, fig.cap="For low count samples, number of variants versus number of batches seen. The most common result is low variants in multiple batches."}
p1 <- ggplot(d.low, aes(total_variants, set)) + geom_point(position="jitter") +
     opts(title="Variants and batches: low") +
     xlab("Sample variants") + ylab("Batches")
p1
```

```{r sample_mean_plot, fig.cap="The mean coverage depth per sample for low and high count variants. The majority of lower coverage calls are in non-bait regions."}
p2 <- ggplot(d, aes(x=DP_sample_mean)) + geom_histogram() + facet_grid(is_low ~ is_bait) +
     opts(title="Depth of coverage: low and high") +
     xlab("Mean coverage depth per sample")
p2
```

```{r total_variants_plot, fig.cap="The overall counts of variants per sample, dominated by low-sample count variants."}
p3 <- ggplot(d, aes(x=total_variants)) + geom_histogram() +
     opts(title="Distribution of variant counts: all") +
     xlab("Total variants")
p3
```


```{r total_variants_low, fig.cap="Overall counts zoomed to low frequency variants, by bait and non-bait regions."}
p4 <- ggplot(d.low, aes(x=total_variants)) + geom_histogram() +
      facet_grid(is_bait ~ .) +
      opts(title="Distribution of variant counts: low") +
      xlab("Total variants")
p4
```

```{r qual_by_bait, fig.cap="Variant quality scores capped at 10000, by bait and variant sample count. Subsetting the data and examining metrics may be a useful way to assign cutoffs for additional variant filtering."}
p5 <- ggplot(d, aes(x=qual_trunc)) + geom_histogram() +
      facet_grid(is_low ~ is_bait) +
      opts(title="Quality score distribution") +
      xlab("Quality score")
p5
```
